Added -q option to silence output

diff --git a/linode_bash_api b/linode_bash_api
--- a/linode_bash_api
+++ b/linode_bash_api
@@ -13,11 +13,12 @@ VERBOSE=0
 VERSION="20110714"
 MACRO=""
 HELP=0
+QUIET=0
 
 #check if curl is installed
 hash curl 2>/dev/null || { echo "Curl is required but is not installed or not in PATH.  Aborting." >&2; exit 1; }
 
-while getopts "hk:f:c:d:vi:F:m:" opt; do
+while getopts "hk:f:c:d:vi:F:m:q" opt; do
 case $opt in
 h)
 #help
@@ -53,6 +54,9 @@ MACRO="$OPTARG"
 F)
 #response format
 DATA="$DATA&api_responseFormat=$OPTARG"
+;;
+q)
+QUIET=1
 ;;
 \?)
 #unknown option
@@ -176,12 +180,24 @@ fi
 
 if [ -z "$MACRO" ]
 then
-    api_request
+    if [ $QUIET -eq 1 ]
+    then
+        api_request > /dev/null
+    else
+        api_request
+    fi
 else
-if ! type $(echo "$MACRO" | sed 's/ .*//') >/dev/null 2>&1
-then
-    echo "Invalid macro command"
-    exit 1
+    if ! type $(echo "$MACRO" | sed 's/ .*//') >/dev/null 2>&1
+    then
+        echo "Invalid macro command"
+        exit 1
+    fi
+    
+    if [ $QUIET -eq 1 ]
+    then
+        $MACRO > /dev/null
+    else
+        $MACRO
+    fi
 fi
-$MACRO
-fi
+
