Added macros and redirected verbose output to stderr
Macros work by specifying functions that use the api_request function with various options to perform common operations, the macros are stored in ~/.linode_bash_api_macros and/or /etc/linode_bash_api_macros two macros are included by default, the first is a test macro that outputs its arguments, the second toggles the read only attribute of a disk specified by linode label and disk label.

diff --git a/linode_bash_api b/linode_bash_api
--- a/linode_bash_api
+++ b/linode_bash_api
@@ -10,34 +10,18 @@ APIKEY=""
 COMMAND=""
 DATA=""
 VERBOSE=0
-VERSION="20110621"
+VERSION="20110714"
+MACRO=""
+HELP=0
 
 #check if curl is installed
 hash curl 2>/dev/null || { echo "Curl is required but is not installed or not in PATH.  Aborting." >&2; exit 1; }
 
-while getopts "hk:f:c:d:vi:F:" opt; do
+while getopts "hk:f:c:d:vi:F:m:" opt; do
 case $opt in
 h)
 #help
-cat <<EOT
-Linode Bash API $VERSION
-options:
--h      Help
--v      Verbose
--F arg     Response format, default bash (easily readable in a shell, formatted from json), options, json wddx or human (html)
--k arg      API Key to use
--f arg      File to get API key from, key must be the only string on the first line
--c arg      The command to run, for a list of commands see http://www.linode.com/api
--d arg      A quote string containing the data to send in "foo=bar&foo2=bar2" format
--i arg      Get data from file if  - is used get data from stdin
-
-If -k or -f are ommited or don't provide an API key then the following loctions are checked
-$HOME/.linode_api
-/etc/linode/api
-
-Detiails of commands you can run can be found at http://www.linode.com/api/
-EOT
-exit 0
+HELP=1
 ;;
 k)
 #api key
@@ -62,6 +46,10 @@ i)
 #read data from file, if - read from stdin
 DATA=`cat $OPTARG`
 ;;
+m)
+#macro
+MACRO="$OPTARG"
+;;
 F)
 #response format
 DATA="$DATA&api_responseFormat=$OPTARG"
@@ -72,6 +60,34 @@ exit 1
 ;;
 esac
 done
+
+if [ $HELP -eq 1 ]
+then
+cat <<EOT
+Linode Bash API $VERSION
+options:
+-h      Help
+-v      Verbose
+-F arg     Response format, default bash (easily readable in a shell, formatted from json), options, json wddx or human (html)
+-k arg      API Key to use
+-f arg      File to get API key from, key must be the only string on the first line
+-c arg      The command to run, for a list of commands see http://www.linode.com/api
+-d arg      A quote string containing the data to send in "foo=bar&foo2=bar2" format
+-i arg      Get data from file if  - is used get data from stdin
+-m "arg"    Run a macro, a quote encased string with at least one space separated argument which is the macro name, subsequent arguments will be passed to the macro as arguments. Macros are bash functions kept in /etc/linode_bash_api_macros or ~/.linode_bash_api_macros
+
+If -k or -f are ommited or don't provide an API key then the following loctions are checked
+$HOME/.linode_api
+/etc/linode/api
+
+Details of commands you can run can be found at http://www.linode.com/api/
+EOT
+if [ -z "$MACRO" ]
+then
+$MACRO
+exit 0
+fi
+fi
 
 if [ -z $APIKEY ]
 then
@@ -91,17 +107,20 @@ echo "No API key specified" >&2
 exit 1
 fi
 
-if [ -z $COMMAND ]
+if [ -z $COMMAND ] && [ -z "$MACRO" ]
 then
 echo "No command specified" >&2
 exit 1
 fi
 
+function api_request
+{
+
 DATA="$DATA&api_key=$APIKEY&api_action=$COMMAND"
 
 if [ $VERBOSE -eq 1 ]
 then
-echo "Running curl -d $DATA $APIURL"
+echo "Running curl -d $DATA $APIURL" >&2
 fi
 
 RESPONSE=$(curl -s -d "$DATA" "$APIURL")
@@ -136,5 +155,26 @@ then
 else
     echo "$RESPONSE"
 fi
+}
 
+if [ -f /etc/linode_bash_api_macros ]
+then
+    . /etc/linode_bash_api_macros
+fi
 
+if [ -f ~/.linode_bash_api_macros ]
+then
+    . ~/.linode_bash_api_macros
+fi
+
+if [ -z "$MACRO" ]
+then
+    api_request
+else
+if ! type $(echo "$MACRO" | sed 's/ .*//') >/dev/null 2>&1
+then
+    echo "Invalid macro command"
+    exit 1
+fi
+$MACRO
+fi
